CREATE DATABASE IF NOT EXISTS sistema_usuarios DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS sistema DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE sistema_usuarios;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  telefone VARCHAR(20) DEFAULT NULL,
  endereco VARCHAR(200) DEFAULT NULL,
  data_nascimento DATE DEFAULT NULL,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  recuperacao_token VARCHAR(255) DEFAULT NULL,
  recuperacao_expira DATETIME DEFAULT NULL,
  email_verificado TINYINT(1) NOT NULL DEFAULT 0,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  confirmacao_token VARCHAR(128) DEFAULT NULL,
  confirmacao_expira DATETIME DEFAULT NULL,
  UNIQUE KEY usuarios_email_unique (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS telefone VARCHAR(20) DEFAULT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco VARCHAR(200) DEFAULT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS data_nascimento DATE DEFAULT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS recuperacao_token VARCHAR(255) DEFAULT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS recuperacao_expira DATETIME DEFAULT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email_verificado TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS is_admin TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS confirmacao_token VARCHAR(128) DEFAULT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS confirmacao_expira DATETIME DEFAULT NULL;
UPDATE usuarios SET is_admin = 1 WHERE id = 1;

CREATE TABLE IF NOT EXISTS logs_sistema (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT DEFAULT NULL,
  nome VARCHAR(100) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  acao VARCHAR(80) NOT NULL,
  detalhes VARCHAR(255) DEFAULT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

USE sistema;

CREATE TABLE IF NOT EXISTS roupas (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(120) DEFAULT NULL,
  tipo VARCHAR(100) NOT NULL,
  tamanho VARCHAR(10) DEFAULT NULL,
  sexo ENUM('Masculino','Feminino','Unissex') DEFAULT NULL,
  estado ENUM('Novo','Semi-Novo','Usado') DEFAULT NULL,
  local_doacao VARCHAR(180) DEFAULT NULL,
  foto_path VARCHAR(255) DEFAULT NULL,
  pausado TINYINT(1) NOT NULL DEFAULT 0,
  id_usuario INT DEFAULT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE roupas ADD COLUMN IF NOT EXISTS titulo VARCHAR(120) DEFAULT NULL;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS tipo VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS tamanho VARCHAR(10) DEFAULT NULL;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS sexo ENUM('Masculino','Feminino','Unissex') DEFAULT NULL;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS estado ENUM('Novo','Semi-Novo','Usado') DEFAULT NULL;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS local_doacao VARCHAR(180) DEFAULT NULL;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS foto_path VARCHAR(255) DEFAULT NULL;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS pausado TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS id_usuario INT DEFAULT NULL;
ALTER TABLE roupas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
